language: node_js
node_js: lts/dubnium
deploy:
  provider: npm
  edge: true
  on:
    tags: true
    repo: TalalYousif/ReactiveTweets
  email:
    secure: jvpBhsr98uAX+Xo+BtNf8uEB7mE3/Mdj4n+PerVcL443LPU67jH4qK3TU1R+Apmm2LfKieBepAtutzTJbSVLgppQdU7fbc4yxC3q+KTQCLtShOa2j/kMi56Cv2rVXnx5TFmJxEdGhfSweaSDnxMhyEJ97hwq4KeeUKu/8b7mj+Yqn5FAvtJoKKEc1GPheNyfxV5nYRLejFXhgMqwQvCnUoHyVvCDBebcFyQOLXxmoNO2nteh1cSytc0jQNjudZIS6DkQIq/rHJI1peGcHoEu3eSche8p5S08mNSAfs3UIrlqruQlRLN87GYc+qgx+UZl2yM+R+ZEHK7+VJYIh7+24PRXjs/Bs8tLPAcUK1oH9/85t+sxc93nF6V5XUot7s53M7GA/LPq0UWL5OlwvWPbYaZonzuXNIwGJLBKxh5RrPXErr3SZwA27kb6bkVG5nKvbYFF3E7jdYnYiqAYfTsO868MGkYN/3HWjamXm77D6trSzh8v5uzX1q0CaBNpCnMwcVk+oSwMTXxv/xp3mG01K+NQ0zu27evudI6/yef4fa7Q7clnU0UZEKmbmKYhqq3yvcdOLR+f8cjvUXu8zmDdJssuSzYAqxxu0GqTTowi5KDyyF8h9LxhfbWnKiVc+Tf4uJ69gUMbOh7WVI0OiiLiGpNOUjnlaPZ5qf6hpjsZsnM=
  api_key:
    secure: f5pOlvB8nqMDLUiIw3s2Vu4OwC8lJqAMuEWdU5TKurGAtLtnxxfaSkL6Yy694PDX/rqgjOwUeVcp+N5MDppIhAzWhz+yMjvAj2d1+/1hTEy39mKMI+wQNO14IDGVEt9NfFBHkcIv9g99jy0K88l9IPOCvd6IEp3msQmNlHFedznk2xWpjhn9qTwXu05LIvjlgUYqFDRg6SQoKaBMxtqEFQmCEin2ejnTaUN5fUes9AMEnrzxJl/8Ca46PbicIU5y+c93Il5vTwbL3ZBV4bFf+fvu1PyzfSXbmJKkrWP09z/coy4CJTw5o3fUSUiat4VCDHYd/b1nPNFaimVUPaqAEVtMLaZ01azr6eDVHtfKOQ51GnkVyAjCOVb4cQG2Lw6V7cHqnWQKsuptPHLSE39U+5d/Zs9JE2WXiU8HIdJ3o6B9VA6eHrazReGMuWk6P4zXqcYDtn0qTYbCT0T8JMqFiMIAnC7Auf2Ibow5gC2Vz1E5b5hj6Rg1kCJWZhWvWKLEpwF+PHxj1fVqb9kjds2Ow6TzncdW6Hhh3zytLPhv9RD6q3Zpx9Qg6Kihv3TFo8LkiQRBDYDZ7geZMzTtUAI/LBhwNa9GT+gWViENLr5AsJZxe6F2BC67H7W6oYSWKM9QB8T0DxzJ/mCbftUzdGLDjCcs3BN0lUWvnVE+V7p6IkE=
