language: node_js
node_js: lts/dubnium
deploy:
  provider: npm
  edge: true
  api_key:
    secure: VUK7gje1KH37J5HPy4lTfPmcKa40fm8YZmEEkTV2zGxB6/f6Rs898pkD68eUQrQ2A10DLGFPpNv/L71LD+1WU6juKS7gx06NJDiILxJqTqaPAJVE/RBp7UPvzV2MQ1Fs5AY/PJJBHDcJJMrVLR+HdpM/20KBLDURr3u7+9TVluIYV4hQuyJruLaAS8bGZ+5o/eTC8efVejaqCqWiXisjAtBNYZf+bsm8MlieFJs/c/enAmS/XZ/RhGhNf0C+LCkO8T78M7dR26IwlxWW+SrvQ6ZZ8BosZWDTDK2grZcol4R5QLN86YYDx+5GbsHXVcmGG6OwQxSbVq77lS5QBKgYA1aQdufMwpIOCAMgEjhbb7UgbPFQ00V3FVebRRR7K6mEdQO9umanS89QywLl0Sp3JcGX6Cj//R/W1GHqGUYJRjr8DSwIeck2fp+k79HVRT3n94ksi2VWOLrY0JfgB1GphcDqRhUIYeLqJVESpqEn0Mdl769PyxruT5DzBATKpye3wWAG7hXnesURsYoqRI1qiEu3VJ6xNt5CJTadRUk8jqY4kgvJeHXVKzr1/ZV8XAdVRuXub/tI6RubsfYw7ibakH6S69YWCzdXD5QhGqO1gfm5ySdl1S4p1pSazT4pNNk9Zr9qQTN51e7P1f4gN8Z6MtlTgZKpUWSm52IXVnlaNqM=
  on:
    tags: true
    repo: TalalYousif/ReactiveTweets
  email:
    secure: jvpBhsr98uAX+Xo+BtNf8uEB7mE3/Mdj4n+PerVcL443LPU67jH4qK3TU1R+Apmm2LfKieBepAtutzTJbSVLgppQdU7fbc4yxC3q+KTQCLtShOa2j/kMi56Cv2rVXnx5TFmJxEdGhfSweaSDnxMhyEJ97hwq4KeeUKu/8b7mj+Yqn5FAvtJoKKEc1GPheNyfxV5nYRLejFXhgMqwQvCnUoHyVvCDBebcFyQOLXxmoNO2nteh1cSytc0jQNjudZIS6DkQIq/rHJI1peGcHoEu3eSche8p5S08mNSAfs3UIrlqruQlRLN87GYc+qgx+UZl2yM+R+ZEHK7+VJYIh7+24PRXjs/Bs8tLPAcUK1oH9/85t+sxc93nF6V5XUot7s53M7GA/LPq0UWL5OlwvWPbYaZonzuXNIwGJLBKxh5RrPXErr3SZwA27kb6bkVG5nKvbYFF3E7jdYnYiqAYfTsO868MGkYN/3HWjamXm77D6trSzh8v5uzX1q0CaBNpCnMwcVk+oSwMTXxv/xp3mG01K+NQ0zu27evudI6/yef4fa7Q7clnU0UZEKmbmKYhqq3yvcdOLR+f8cjvUXu8zmDdJssuSzYAqxxu0GqTTowi5KDyyF8h9LxhfbWnKiVc+Tf4uJ69gUMbOh7WVI0OiiLiGpNOUjnlaPZ5qf6hpjsZsnM=
